name: Create Release Test

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./DataGridVueDotnet
    steps:
      - uses: actions/checkout@v4
      - name: Escape version
        run: echo "ESCAPED_VERSION=$(echo "${{ vars.TEST_VERSION }}" | sed 's/[^^]/[&]/g; s/\^/\\^/g')" >> $GITHUB_ENV
      - name: Parse release notes
        run: grep -Pzo '(?<=### v${{ env.ESCAPED_VERSION }}\n)\X+(?=\n\n)' ../README.md > release_notes.txt
      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ vars.TEST_VERSION }}
          release_name: v${{ vars.TEST_VERSION }}
          body_path: ./release_notes.txt
